
export const firebaseConfig = {
    apiKey: "AIzaSyAOrh8VpH_wQpns9mkZ_pI0h_CeH7atWgI",
    authDomain: "a3mali-aa343.firebaseapp.com",
    projectId: "a3mali-aa343",
    storageBucket: "a3mali-aa343.firebasestorage.app",
    messagingSenderId: "480778702343",
    appId: "1:480778702343:web:49ab412ca7457ba76fa4a2",
    measurementId: "G-JGTCTLL94V"
  };
export const APP_CONFIG = {
  name:          'أعمالي',
  nameEn:        'A3mali',
  version:       '1.0.0',
  defaultLang:   'ar',
  defaultTheme:  'light',
  itemsPerPage:  25,
  taxRate:       0.11,
  currency:      'ل.س',
  currencyEn:    'SYP',

  offlineDB:     'a3mali_offline',
  offlineVersion: 1,

  roles: ['super_admin', 'company_admin', 'manager', 'accountant', 'cashier', 'employee'],

  collections: {
    COMPANIES:           'companies',
    BRANCHES:            'branches',
    USERS:               'users',
    ROLES:               'roles',
    PERMISSIONS:         'permissions',
    CUSTOMERS:           'customers',
    SUPPLIERS:           'suppliers',
    PRODUCTS:            'products',
    CATEGORIES:          'categories',
    WAREHOUSES:          'warehouses',
    INVENTORY_MOVEMENTS: 'inventory_movements',
    SALES:               'sales',
    INVOICES:            'invoices',
    PURCHASES:           'purchases',
    PAYMENTS:            'payments',
    EXPENSES:            'expenses',
    ACCOUNTS:            'accounts',
    TRANSACTIONS:        'transactions',
    EMPLOYEES:           'employees',
    ATTENDANCE:          'attendance',
    PAYROLL:             'payroll',
    CASHIER_SESSIONS:    'cashier_sessions',
    RECEIPTS:            'receipts',
    REPORTS:             'reports',
    SETTINGS:            'settings',
    AUDIT_LOGS:          'audit_logs',
  },
};
